service: aws-lambda-nodejs-rest

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    timeout: 600 # seconds
    memorySize: 128 # mb
